############################################################
#
#
#
############################################################
include $(ONL)/make/config.mk

MODULE := x86_64_ufispace_s9180_32x
AUTOMODULE := x86_64_ufispace_s9180_32x
include $(BUILDER)/definemodule.mk
